arm:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
arm_and_finger:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
finger:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
